### ISSUE TITLE
Questions about this GEM

### ISSUE THREAD

**Issue by nicolas-besnard** [brandonhilkert/sucker_punch#101]
Firstly : thank you for this gem, it really works great ! I was looking for a fast and not database dependant : I found it !

Secondly, I have some questions about the gem :
* How is it working ? As other background jobs gem use database, yours don't. How the queue is manage ?
* Is there any way to do recurrent job ?

**Comment by weaksauce** [comment]
> How is it working ? As other background jobs gem use database, yours don't. How the queue is manage ?

It uses an in memory threading and concurrency library. when the process controlling things is restarted, the in memory queue is lost. This library is intended to be used for background jobs that immediately run or are not mission critical if they are lost due to server restart.

**Comment by brandonhilkert** [comment]
@weaksauce Summed it up well. All answers are accurate. I'll add some context to the `README` better summarizing these questions.

**Comment by brandonhilkert** [comment]
Add detail to the `README` - https://github.com/brandonhilkert/sucker_punch#sucker-punch
