### ISSUE TITLE
Job progress

### ISSUE THREAD

**Issue by nicolas-besnard** [brandonhilkert/sucker_punch#103]
I'm using this gem for background job, and I really love it. No need to host an other DB, no need to launch worker : really great for email, CSV parsing and stuff like that.

Now, I'd like to add a new feature to my Job : I want to show a progress bar to my user (when I'm parsing a CSV for example). The idea is to do something like [progress_job](https://github.com/d4be4st/progress_job).

What do you thing of it ? I'm not asking you to implement it, I'll. I'm just wondering if is there any possibility to add it to your gem ?

**Comment by brandonhilkert** [comment]
I'd be interested to see some code if it's something you're interested in.

On Friday, March 13, 2015, Nicolas Besnard <notifications@github.com> wrote:

> I'm using this gem for background job, and I really love it. No need to
> host an other DB, no need to launch worker : really great for email, CSV
> parsing and stuff like that.
>
> Now, I'd like to add a new feature to my Job : I want to show a progress
> bar to my user (when I'm parsing a CSV for example). The idea is to do
> something like progress_job <https://github.com/d4be4st/progress_job>.
>
> What do you thing of it ? I'm not asking you to implement it, I'll. I'm
> just wondering if is there any possibility to add it to your gem ?
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/brandonhilkert/sucker_punch/issues/103>.
>


-- 

------------------------------------
*Build a Ruby Gem is available!
<http://brandonhilkert.com/books/build-a-ruby-gem/?utm_source=gmail-sig&utm_medium=email&utm_campaign=gmail>*

http://brandonhilkert.com
