### ISSUE TITLE
Add hook to job

### ISSUE THREAD

**Issue by nicolas-besnard** [brandonhilkert/sucker_punch#104]
I'm currently digging on many job queue gem : Resque, Sidekiq and Delayed Job. Many of them add hook such as `before`, `after`, `success`, `error` or `failure`. Do you think it can be something useful for this gem ?

**Comment by brandonhilkert** [comment]
I haven't had the need, but I could imagine a scenario where it'd be
useful.

On Saturday, March 14, 2015, Nicolas Besnard <notifications@github.com>
wrote:

> I'm currently digging on many job queue gem : Resque, Sidekiq and Delayed
> Job. Many of them add hook such as before, after, success, error or
> failure. Do you think it can be something useful for this gem ?
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/brandonhilkert/sucker_punch/issues/104>.
>


-- 

------------------------------------
*Build a Ruby Gem is available!
<http://brandonhilkert.com/books/build-a-ruby-gem/?utm_source=gmail-sig&utm_medium=email&utm_campaign=gmail>*

http://brandonhilkert.com
