### ISSUE TITLE
Recurring jobs

### ISSUE THREAD

**Issue by nicolas-besnard** [brandonhilkert/sucker_punch#105]
Is there any way to do recurring jobs with this gem ? I plan to use the [whenever gem](https://github.com/javan/whenever). Do you know any other solution ?

**Comment by brandonhilkert** [comment]
@nicolas-besnard what specifically are you looking to do? There's nothing stopping you from writing a rake task that invokes a bunch of sucker punch jobs, and then using whenever to trigger that rake task at the frequency of your choice.

**Comment by nicolas-besnard** [comment]
I'd like to execute a jobs each 3 hours to create some statistics on my model. It's essentially calculating data to export them on an external DB.

**Comment by brandonhilkert** [comment]
That makes sense. Do you _have_ to use Sucker Punch? Currently there is no automated way to do this, but the combo of whenever and rake probably make the most sense.

**Comment by acrogenesis** [comment]
Any updates on this issue?

**Comment by brandonhilkert** [comment]
@acrogenesis What updates are you looking for? I don't believe this is something Sucker Punch should be responsible for. There are a number of tools out there that do this independent of the background processing library. Let me know if I've misinterpreted what you're interested in.
