### ISSUE TITLE
Pool size

### ISSUE THREAD

**Issue by bighoax** [brandonhilkert/sucker_punch#106]
Hello, I haven't been able to find this info so I've opened a new issue, even though it's not really an issue. I use jRuby with rails, my question is there a way to configure a worker pool? 

I'm currently using this gem for sending emails, works awesome so far.

**Comment by brandonhilkert** [comment]
What specifically about it? Each job is given its own pool.

On Monday, March 23, 2015, bighoax <notifications@github.com> wrote:

> Hello, I haven't been able to find this info so I've opened a new issue,
> even though it's not really an issue. I use jRuby with rails, my question
> is there a way to configure a worker pool?
>
> I'm currently using this gem for sending emails, works awesome so far.
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/brandonhilkert/sucker_punch/issues/106>.
>


-- 

------------------------------------
*Build a Ruby Gem is available!
<http://brandonhilkert.com/books/build-a-ruby-gem/?utm_source=gmail-sig&utm_medium=email&utm_campaign=gmail>*

http://brandonhilkert.com

**Comment by bighoax** [comment]
Hi Brandon,

What is the size of the pool given to each job, is there a default value?

Also from what I understand from here :
https://github.com/celluloid/celluloid/wiki/Pools

I can specify the pool size. Can I somehow configure pool size for a particular job?
I'm currently using this gem to send out emails in the background from a job. 

Let's say that the pool size (number of available workers) is 5, but at the given time there is 10 users doing some action which requires email notification, so it should only send 5 each time. Is that how it works now?

I just moved from Heroku and running on MRI to jruby on AWS and managed infrastructure, so there were so many things taken care of by Heroku and now I need to research what every component does in details. 

THanks

**Comment by brandonhilkert** [comment]
This is covered in the README. 

![screen shot 2015-03-24 at 12 47 03 pm](https://cloud.githubusercontent.com/assets/744212/6807282/ee7362c8-d223-11e4-8a70-2049b1fc1073.png)

Yup, it works as you describe.

**Comment by bighoax** [comment]
thanks @brandonhilkert I was reading the README late last night and missed that part. 
Thanks for getting back at me I'll close this issue.
