### ISSUE TITLE
Introducing SuckerPunch breaks Celluloid::Notifications functionality

### ISSUE THREAD

**Issue by sslotsky** [brandonhilkert/sucker_punch#114]
I recently introduced SuckerPunch to do some work that I was previously doing with DelayedJob. I was already using Celluloid actors & notifications successfully in my project to do some other processing. The newly wired SuckerPunch jobs work fine, but attempting to execute the code that uses notifications raises a ```DeadActorError``` with the message "notifications fanout actor not running"

This error is raised as soon as I instantiate a subscriber:

```
class SnapshotListener
  include Celluloid
  include Celluloid::Notifications
  include Celluloid::Logger

  def initialize(snapshot)
    @snapshot = snapshot
    subscribe(register_channel, :schedule_page)
    subscribe(complete_channel, :complete_page)
  end

  ...
end
```

This code is executed from the main thread in an ActiveRecord callback after a form is submitted. When I remove ```SuckerPunch``` from my project, the notifications work again.

**Comment by sslotsky** [comment]
My mistake here, it was not SuckerPunch but rather a websockets library that was causing the problem. Closing.

**Comment by brandonhilkert** [comment]
It may be related to https://github.com/brandonhilkert/sucker_punch/pull/113

**Comment by sslotsky** [comment]
That seems likely! I will keep this open until that is merged and retest. Thanks!

**Comment by brandonhilkert** [comment]
v `1.5.0` has been released. Please try that version and see if you still have issues.

**Comment by brandonhilkert** [comment]
Closing since I haven't heard back.

**Comment by sslotsky** [comment]
@brandonhilkert Sorry I did not respond, this is indeed fixed. Thanks!

**Comment by brandonhilkert** [comment]
Great to hear. Thanks for the follow-up!
