### ISSUE TITLE
Max number of workers

### ISSUE THREAD

**Issue by mradmacher** [brandonhilkert/sucker_punch#115]
It is a great library and very useful for me. 
But in my current project I need around 200 of concurrent workers. Is there any reason for choosing 100 as a [maximum number of workers](https://github.com/brandonhilkert/sucker_punch/blob/master/lib/sucker_punch/queue.rb#L25)?

**Comment by brandonhilkert** [comment]
It was somewhat arbitrary. I'll bump it up. Just didn't want anyone to shoot themselves in the foot.

**Comment by brandonhilkert** [comment]
Bumped to 200 in version `1.5.0`.

**Comment by mradmacher** [comment]
That is awesome. Thank you.
