### ISSUE TITLE
pass arguments to exception hook so I know what exactly failed

### ISSUE THREAD

**Issue by grosser** [brandonhilkert/sucker_punch#118]
Just got an exception ... but not Idea what failed since I don't know the job arguments ...
how about this interface ?

```Ruby
SuckerPunch.exception_handler { |ex, job_class, args| Rollbar.error(ex, "#{job_class}: #{args.join(' ')}") }
```

alternatively appending the exception message with the job arguments before sending it off

@brandonhilkert

**Comment by brandonhilkert** [comment]
PRs welcomed :+1:

**Comment by grosser** [comment]
looks like sucker_punch is not in control of the perform methods / we could not capture exceptions ...
I was hoping to do `SuckerPunch.exception_handler { |ex, job_class=nil, args=nil|` and then let celluloid and suckerpunch call the same handler ...
