### ISSUE TITLE
Do not overwrite .new / leave simple perform alone

### ISSUE THREAD

**Issue by grosser** [brandonhilkert/sucker_punch#120]
I felt it hard to test my jobs since .perform/.new are already overwritten,
would it make sense that .new and .perform behave normally and just .async triggers celluloid magic ?

@brandonhilkert 

FYI doing this to keep my job testable:

```Ruby
class BackgroundJobTestable
  def perform
    ...
end

class BackgroundJob < BackgroundJobTestable
  include SuckerPunch::Job
  workers 2
end
```

**Comment by brandonhilkert** [comment]
Celluloid is overriding those methods. Unless Celluloid is completely abandoned, I don't see a clear way to avoid this. What issues are you having with testing?

**Comment by grosser** [comment]
I was hoping to not include Celluloids and just make `def async; Celluloid.async(self);end` or something like that, basically keeping the class 'plain' ... but that would break a bunch of stuff ... so just keeping my inheritance workaround ...
