### ISSUE TITLE
Jobs not processed after a little while

### ISSUE THREAD

**Issue by navjeetc** [brandonhilkert/sucker_punch#132]
I am using Rails 4.2.3, Active job, sucker punch1.5.1, Apache 2.2.31 and Passenger 5.0.15. After process some jobs successfully, the active job does not seem to process any more jobs. But when I restart Apache, the processing starts again for subsequent jobs. Do I need to tweak some setting in Passenger or Sucker Punch to fix this issue?

**Comment by brandonhilkert** [comment]
Does the same thing happen if you setup sucker punch without going through
active job?

On Monday, October 12, 2015, Navjeet <notifications@github.com> wrote:

> I am using Rails 4.2.3, Active job, sucker punch1.5.1, Apache 2.2.31 and
> Passenger 5.0.15. After process some jobs successfully, the active job does
> not seem to process any more jobs. But when I restart Apache, the
> processing starts again for subsequent jobs. Do I need to tweak some
> setting in Passenger or Sucker Punch to fix this issue?
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/brandonhilkert/sucker_punch/issues/132>.
>


-- 

------------------------------------
*Build a Ruby Gem is available!
<http://brandonhilkert.com/books/build-a-ruby-gem/?utm_source=gmail-sig&utm_medium=email&utm_campaign=gmail>*

http://brandonhilkert.com

**Comment by navjeetc** [comment]
I have not tried that yet. I will try it and get back.

**Comment by navjeetc** [comment]
I was able to replicate the issue without going thru active job. In fact now even if I restart apache, the jobs are not running any more at all.

**Comment by navjeetc** [comment]
Standby on that. I need to do some more testing. There could be a problem with my php script which is posting jobs.

**Comment by navjeetc** [comment]
I confirm that the issue still exists whether using active job or not.

**Comment by brandonhilkert** [comment]
Can you provide a sample app repo that reproduces?


------------------------------------
*Build a Ruby Gem is available!
<http://brandonhilkert.com/books/build-a-ruby-gem/?utm_source=gmail-sig&utm_medium=email&utm_campaign=gmail>*

http://brandonhilkert.com

**Comment by navjeetc** [comment]
Brandon, I have given u access to code at https://github.com/navjeetc/chat (use master branch)

**Comment by navjeetc** [comment]
Any luck looking into this issue?

**Comment by brandonhilkert** [comment]
I've not been able to look in to this. Have you tried reproducing with unicorn or another app server? Need to isolate the factors here to try and figure out which piece is causing the issue.

**Comment by navjeetc** [comment]
I was able to recreate the issue with Nginx and unicorn. Again the issue starts after a while and I have not seen any pattern when. I see the jobs being enqueued but not performed. BTW the job invokes an ActiveModel, which sends a message to a xmpp chat room.

**Comment by brandonhilkert** [comment]
Haven't had this reported by any one else. My hunch is it has something to do with the application, but I can't say for sure.
