### ISSUE TITLE
Make Sucker Punch stay quiet on exit

### ISSUE THREAD

**Issue by dhh** [brandonhilkert/sucker_punch#158]
We're using Sucker Punch for development testing with Basecamp 3 (thanks!) and I just tried v2. Lovely to see it do without the Celluloid dependency, but I'd love if it also would stay quiet on exit. Here's what I'm getting:

```
Marbella-iMac:bc3 david$ r c
Running via Spring preloader in process 7787
Loading development environment (Rails 5.0.0.beta1)
irb(main):001:0> exit
Shutdown triggered...executing remaining in-process jobs
Remaining jobs have finished
All is quiet...byebye
```

Maybe redirect output like that to a log file and make that optional?

**Comment by brandonhilkert** [comment]
Hey David! The [logger can be set](https://github.com/brandonhilkert/sucker_punch#logger). Would that work for you?

**Comment by dhh** [comment]
Ah, I see that the logger actually already is set to Rails.logger by
default! So it's actually doing "the right thing". It's just still overly
verbose, imo, when you start the console that it gives you that much info
on exit. Especially since it isn't prefixed.

What do you think about just staying quiet unless there are jobs to run
still pending? In the tradition of "if all is well, don't tell".

**Comment by brandonhilkert** [comment]
Fair point. That makes sense. I'll push a change for that later today and let you know.

**Comment by dhh** [comment]
🙏

**Comment by brandonhilkert** [comment]
Give `2.0.0.beta2` a shot and lemme know!

**Comment by dhh** [comment]
Perfecto! Thanks again for the crazy fast turn-around.

**Comment by brandonhilkert** [comment]
@dhh FYI - `2.0.0` was officially released this morning. No changes from `2.0.0.beta2`.

**Comment by dhh** [comment]
👍
