### ISSUE TITLE
Feature request: async on class methods.

### ISSUE THREAD

**Issue by hey-jude** [brandonhilkert/sucker_punch#164]
Sidekiq can use delay() method on class method.
https://github.com/mperham/sidekiq/wiki/Delayed-extensions

How about sucker_punch's async()?

**Comment by brandonhilkert** [comment]
You can still use the old sync (`.new.async`) with the backwards compatibility include. Right now, I'd prefer to let this DSL bake for awhile before introducing any more changes.
