### ISSUE TITLE
Setting priority

### ISSUE THREAD

**Issue by brauliobo** [brandonhilkert/sucker_punch#171]
I think that Sucker Punch jobs (and threads) should run in a lower priority so they don't slow down the app. Is it so? Is there an option to change it?

**Comment by brandonhilkert** [comment]
There's currently no option for that. Limiting the workers for an intense job might be one way around it. But due to the GIL, the effectiveness of this will still be mediocre at best. Happy to look at PRs if you're interested in putting something together.
