### ISSUE TITLE
ActiveJob and self.queue_adapter

### ISSUE THREAD

**Issue by phlegx** [brandonhilkert/sucker_punch#176]
Hi!
I use **Rails 4.2.3** and the latest sucker_punch version 2.0.2. How can I set the number of workers?

Here my job class:

```ruby
class TestJob < ActiveJob::Base
  self.queue_adapter = :sucker_punch
  queue_as :high
  workers 10

  def perform
  end
end
```

I get the following error: ` NoMethodError: undefined method 'workers' for TestJob:Class`
Read here: https://github.com/rails/activejob/issues/47

**Comment by brandonhilkert** [comment]
I believe you'd have to use Sucker Punch as documented without `ActiveJob` to make that work.
