### ISSUE TITLE
Unique jobs?

### ISSUE THREAD

**Issue by xanview** [brandonhilkert/sucker_punch#177]
Is there anyway to make sure that before I add a new job, there are no jobs like it already in the queue or are being processed?

**Comment by brandonhilkert** [comment]
Unfortunately there is not.

On Friday, May 6, 2016, Roman Gaufman <notifications@github.com> wrote:

> Is there anyway to make sure that before I added a new job, there are no
> jobs like it already in the queue or are being processed?
>
> —
> You are receiving this because you are subscribed to this thread.
> Reply to this email directly or view it on GitHub
> <https://github.com/brandonhilkert/sucker_punch/issues/177>
>


-- 

------------------------------------
http://brandonhilkert.com

**Comment by rmoriz** [comment]
Even when I set `workers` to 1, it seems that sometimes more than one worker is running.

**Comment by brandonhilkert** [comment]
@rmoriz min. # of threads is 2.

**Comment by rmoriz** [comment]
@brandonhilkert with Celluloid we could monkeypatch the min # of threads to 1 to get a serial execution :/

**Comment by brandonhilkert** [comment]
@rmoriz Actually, now that I look at it, it appears it should go down to 1. What makes you believe it's not?

Can you open a separate issue related to that alone?

**Comment by rmoriz** [comment]
Okay, I've also found another strange issue. Will open new issues

**Comment by rmoriz** [comment]
Okay my issue was: Unicorn + Sinatra + Sucker Punch. 3 unicorn workers * 1 Sucker Punch worker = 3 parallel jobs. 

I've reduced the worker number in our setup (internal very-very low api/callback service) to fix the problem.
