### ISSUE TITLE
How to find sheduling Job ID

### ISSUE THREAD

**Issue by shashi-we** [brandonhilkert/sucker_punch#184]
Is there any way to find scheduling job id and kill that?

I saw log where it is show 

[ActiveJob] Enqueued ActionMailer::DeliveryJob (Job ID: d4eb1d53-3497-43c1-b7c7-e55e05ad9fcd) to SuckerPunch(mailers) with arguments: "UserMailer", "send_notification", "deliver_now", gid://essay-review-app/User/40, gid://essay-review-app/User/38, gid://essay-review-app/Attachment/292

**Comment by brandonhilkert** [comment]
Unfortunately not.
