### ISSUE TITLE
No Way to Set Workers When Used Via ActiveJob

### ISSUE THREAD

**Issue by thedillonb** [brandonhilkert/sucker_punch#189]
Setting workers is done via the Job instance. However, via ActiveJob, that interface is abstracted from us. There's no way to then set the `workers` for that particular job.

**Comment by brandonhilkert** [comment]
Yeah, I hear you. I don't use ActiveJob, so it hasn't been a huge deal for me, but open to PR's if that's something that's even possible (I don't know if it is).

**Comment by grosser** [comment]
active_job implementation is here: https://github.com/rails/rails/blob/master/activejob/lib/active_job/queue_adapters/sucker_punch_adapter.rb

so could do:

```
ActiveJob::QueueAdapters::SuckerPunchAdapter::JobWrapper.workers 1
```

to force single-file execution of all jobs ...

**Comment by tpiaggio** [comment]
@grosser Where should we exactly put that line in our code? I've tried in so many places but it doesn't seem to be working, they are always 2 jobs being processed at the same time.

I have tried on the job class, on the sucker_punch initializer the controller calling the job.. but no luck.

Thanks in advance!

**Comment by grosser** [comment]
@tpiaggio updated the comment, hope that is clearer :)

**Comment by phlegx** [comment]
Is there a way to set SuckerPunch workers globally?

**Comment by brandonhilkert** [comment]
@phlegx Not currently
