### ISSUE TITLE
Jobs getting killed

### ISSUE THREAD

**Issue by solars** [brandonhilkert/sucker_punch#191]
Hi there,

I've got an application that updates data in the background via sucker punch.

Due to delays caused by a missing index I noticed that certain jobs did not complete - probably because they took too long.

I didn't find any details about how sucker_punch handles this, the apps are running under passenger.
The shutdown_timeout is only used application shutdowns, right?

**Comment by brandonhilkert** [comment]
To be specific, `shutdown_timeout` is not used anywhere else in the code for any kind of execution timeout. I suppose there could be questions about how passenger would handle long-running threads like that. I'm not familiar with how it works to know if that could potentially be a problem. But there's nothing in SP that would cut it off intentionally.

**Comment by solars** [comment]
Thanks for the clarification! I thought so - trying to find out how passenger limits this.
