### ISSUE TITLE
Needed Memory Backup Or Redis, ActiveRecord Support 

### ISSUE THREAD

**Issue by likelazyeyes** [brandonhilkert/sucker_punch#195]
We need this feature because when Rails restart, our background jobs lost. 

There is a gem adding redis support but it's development not active. https://github.com/chemica/concussion/

I think active record support can be excarted from delayed job. 

The reason is our jobs queqee must always be avaible. I think it can handle this via its own way. If we access its quequue which in memory, quequue can write the active_record table via active_job, ex;hourly backup. Via an initializer we must load jobs to memory from active record. So the quequue in memory read and write access will look pretty much.

Sucker punch is a great solution but only this think  missing. Lets do something to build this missing and make more powerful it. 

If we cant fix this, i have to go another one and worker costs.

**Comment by brandonhilkert** [comment]
Hi there!

Thanks for your interest in Sucker Punch. While I completely understand why you'd want this feature, persistence was never something intended for Sucker Punch. My recommendation if that's needed is to always use Sidekiq. It's a superior library in almost all ways and Sucker Punch is unlikely to do better at the same features. I recognize that using a library like Sidekiq requires additional workers, and additional cost, but Sucker Punch was never meant to fill that niche and as a result, would likely never be added to this repo. 

Feel free to development an extension for these features. Good luck!
