### ISSUE TITLE
How can controller know when the job is done?

### ISSUE THREAD

**Issue by arefinbigfuture** [brandonhilkert/sucker_punch#199]
Is there any way to let controller know that the job is done? I am using a ajax loading image until my process finishes. But after using sucker_punch, the loading image goes invisible but the process keeps running in background. How can I solve this issue in sucker_punch?

Thanks

**Comment by brandonhilkert** [comment]
There is no job monitoring. I would capture that in the application. Something like maybe have a database field `processed_at`, that's nil to start and gets a timestamp when the job completes. Your loader can poll an endpoint that checks if the job is complete every couple seconds, and once complete moves on to the next step in the application.

**Comment by shobhitic** [comment]
If you have actioncable, you can use that as well as a callback for when the job completes. Client subscribes to a channel specific for that job, and receives data from the sucker punch worker.
