### ISSUE TITLE
Is there a way to retry a failed job?

### ISSUE THREAD

**Issue by basiszwo** [brandonhilkert/sucker_punch#200]
In my application I am sending emails with sucker punch asynchronously. 

Sometimes the mail server has outages which results in exceptions.

I am wondering if there is a way to somehow retry a job after a couple of seconds?

**Comment by brandonhilkert** [comment]
Sucker Punch doesn't provide that, but I don't think anything's stopping you from building it in to the job:

```
class LogJob
  include SuckerPunch::Job

  def perform(event)
    Log.new(event).track
  rescue SeverError => e
    LogJob.perform_in(2, event) # Enqueue the job for a few seconds later
  end
end

**Comment by basiszwo** [comment]
thank you for the quick answer and for pointing me to `perform_in`!

**Comment by jaredbeck** [comment]
> Sucker Punch doesn't provide [a retry feature] .. -2017

Is this still true in 2023? Thanks for the gem!

**Comment by brandonhilkert** [comment]
Nothing has changed. You're welcome :)
