### ISSUE TITLE
Allow to filter sensitive parameters

### ISSUE THREAD

**Issue by denisenkom** [brandonhilkert/sucker_punch#202]
Currently sucker_punch would log queued jobs and it's parameters.

Sometimes such parameters can contain sensitive data, like passwords.  It should be possible to specify a list of sensitive parameter names and sucker_punch should sensor values for such parameters.  Similar to that http://guides.rubyonrails.org/action_controller_overview.html#parameters-filtering

**Comment by brandonhilkert** [comment]
Thanks for the interest! I view Sucker Punch as a specific tool, not a general framework. You can [set the logger](https://github.com/brandonhilkert/sucker_punch#logger), which should allow you to develop a logger that excludes the information you mention. Further, if it's used in a Rails context, you could probably tap in to the existing tools there to do the same thing. 

It's unlikely I'd be able to make a logger better than the current ones out there. I'd prefer to keep sucker punch very specific and rely on community tools for functions like this.
