### ISSUE TITLE
Using SuckerPunch with Bunny

### ISSUE THREAD

**Issue by blanchma** [brandonhilkert/sucker_punch#207]
Whenever I try to open a channel using Bunny in SuckerPunch I get a Timeout::Error. I know this is a question for Bunny library but I want to ask if in your experience the library with Ruby 2.3.1 could be having a concurrency issue?

**Comment by brandonhilkert** [comment]
I haven't used Bunny before, but Sucker Punch uses https://github.com/ruby-concurrency/concurrent-ruby under the covers. So if there was any issue, it'd be related to it.

A quick search didn't yield any results for "Bunny" in their issues list. Might be worth asking over there though, in case there's something obvious we're missing.

**Comment by blanchma** [comment]
Thanks for your quick answer. I'm using an async job to run async methods of classes. Can a crash in one worker of a job affect others workers?
