### ISSUE TITLE
Store tenant info

### ISSUE THREAD

**Issue by rssluca** [brandonhilkert/sucker_punch#213]
Hi,

I am using the apartment gem and was wondering whether it would be possible to store the tenant id when creating a job.

Thanks!!

Luca

**Comment by brandonhilkert** [comment]
I think this is more of an implementation question. You can always subclass a parent job class that would define a setter or default list of arguments that are required when invoking a job, such that it's accessible from without the job code. I think this would be similar to how you would do it in another other background job processing library, not unique to sucker punch.
