### ISSUE TITLE
update rails advice to use executor or reloader?

### ISSUE THREAD

**Issue by jjb** [brandonhilkert/sucker_punch#247]
The [readme shows](https://github.com/brandonhilkert/sucker_punch/blob/master/README.md#activerecord-connection-pool-connections) how to manually achieve the most important parts of that. Maybe it should be updated to use the rails [executor or reloader](https://guides.rubyonrails.org/threading_and_code_execution.html#executor) instead?

> Prior to Rails 5.0, some of these were handled by separate Rack middleware classes (such as ActiveRecord::ConnectionAdapters::ConnectionManagement), or directly wrapping code with methods like ActiveRecord::Base.connection_pool.with_connection. The Executor replaces these with a single more abstract interface.

**Comment by jjb** [comment]
Then again...

> Rails automatically wraps web requests and Active Job workers

So maybe executor _and_ with_connection are irrelevant if used with ActiveJob?

**Comment by brandonhilkert** [comment]
I'm honestly not sure. I don't use ActiveJob so not sure what it does on its own.

**Comment by jjb** [comment]
gotcha - I had some discussion about something similar here:

https://github.com/bensheldon/good_job/pull/389#issuecomment-1015990096

i'll close this out for now, may be helpful for people searching in future, or maybe someone more opinionated/knowledgable in future will suggest a change
