### ISSUE TITLE
ArgumentError: A copy of MyTestJob has beed removed from the module tree but is still active!

### ISSUE THREAD

**Issue by rwz** [brandonhilkert/sucker_punch#49]
Hi,

I'm trying to run SuckerPunch in development mode and run into a problem when Rails reloads classes between requests, but Queue has a class instance and tries to use it resulting with subj error.

Is there a way around this? I don't want to switch to inline mode for development.

**Comment by mvdamme** [comment]
I'm experiencing the same problem on a Rails 4.1.12 app. I was originally using sucker_punch 1.0.5, but upgrading to the latest released version (1.5.1) didn't help.

If I add a sleep call to the 'main' thread (the one creating the job) so the job finishes before the request (which redirects and triggers a subsequent reload) the problem disappears.

Any suggestions?

**Comment by shakycode** [comment]
@brandonhilkert I'm seeing this same problem both in development and in productions. Rails 4.2.4, Ruby  2.2.3.  My job sends a twilio message and calls a mailer each one taking a second or so to perform.  Should I break these into two separate jobs and have them fire in parallel?

**Comment by brandonhilkert** [comment]
Something like http://ruby-concurrency.github.io/concurrent-ruby/Concurrent/CountDownLatch.html is a great way to detect whether the jobs in the other threads have finished.
