### ISSUE TITLE
Tracking threads

### ISSUE THREAD

**Issue by aaani** [brandonhilkert/sucker_punch#56]
I am looking for a way to kill jobs just in case they are hung or taking forever. Is there any way to track/list existing jobs?

**Comment by JoeZ99** [comment]
that's too bad!! The library is great otherwise.

Does this means that the only way of getting rid of stalled processes is by restarting the rails server? Is there any sort of "panic button" somewhere in the code?

**Comment by brandonhilkert** [comment]
@JoeZ99 Not sure what you mean by "stalled processes". The threads are running in the web process. There is currently no manual way to manipulate the queue unless you dig in the internals of Celluloid.

**Comment by JoeZ99** [comment]
@brandonhilkert , I mean processes that, for some kind of bad programming (which I'm very prone to do, btw ;-) ), enters into and endless loop of the sort,

anyway, txs for the code, it's incredibly convenient.
