### ISSUE TITLE
check some condition

### ISSUE THREAD

**Issue by andreydeineko** [brandonhilkert/sucker_punch#61]
Hello all,

not sure, if it is an issue, because I did not experience a problem yet.. 
But still. I wonder, if sucker_punch is a tool corresponding to my need.

I want to check if an object's attribute was changed within 24 hours after creation, and if yes - send an email notification. The problem is to set this checking not once, but periodically (say, every 15 minutes).

I have deployed my app on Heroku and know about their solutions, but currently i seek for free of charge solution.

Thank you in advance!

**Comment by lulalala** [comment]
Having a similar need here, I need to do some web crawling periodically.

I don't use Heroku, so I am thinking of a pure SuckerPunch solution.

I think this would work:

```
class FooJob
  include SuckerPunch::Job

  def perform(event)
    # Do things
    FooJob.perform_in(60 * 50)
  end
end
```
