### ISSUE TITLE
Proper way to use external exception management tool?

### ISSUE THREAD

**Issue by mm53bar** [brandonhilkert/sucker_punch#78]
I use rollbar.com as an external exception management tool. It isn't covered in your README, but it looks like the right way for me to send exceptions in my jobs to rollbar is to create a `config/initializers/sucker_punch.rb` file that contains:

`SuckerPunch.exception_handler { |ex| Rollbar.report_exception(ex) }`

Is that the correct way for me to add the exception handler in?

If that's the case then you should add that into your README. I'd be happy to submit a pull request to that effect if I've got the syntax correct.

**Comment by openface** [comment]
#109
