### ISSUE TITLE
Memoized method values

### ISSUE THREAD

**Issue by larryfox** [brandonhilkert/sucker_punch#83]
Not sure if this is an issue with sucker_punch or celluloid in general (or if it's expected behavior), but memoizing methods doesn't play well with one of them. Here's a basic example:

``` ruby
require 'sucker_punch'

class MyJob
  include SuckerPunch::Job

  def perform(msg)
    File.open("#{msg}.txt", 'w+') { |io| io << expensive_method(msg) }
  end

  def expensive_method(msg)
    @expensive_method ||= "Your message was: #{msg}"
  end
end

MyJob.new.perform("1")
MyJob.new.perform("2")
MyJob.new.perform("3")
MyJob.new.perform("4")
```

Which leaves me with the following files:

```
1.txt ==> "Your message was: 1"
2.txt ==> "Your message was: 2"
3.txt ==> "Your message was: 1"
4.txt ==> "Your message was: 2"
```

Seems to be tied to the number of workers. Easy enough to work around but a gotcha non the less.

**Comment by hmnhf** [comment]
@brandonhilkert Seems you forgot to add a note about this.
