### ISSUE TITLE
Implement delay for active job adapter

### ISSUE THREAD

**Issue by kinnrot** [brandonhilkert/sucker_punch#93]
error NotImplementedError=== ["/Users/chen/.rbenv/versions/2.1.5/lib/ruby/gems/2.1.0/gems/activejob-4.2.0/lib/active_job/queue_adapters/sucker_punch_adapter.rb:27:in `enqueue_at'"

the basic functionality supports it, so why no implementation for the adapter?

**Comment by davidcpell** [comment]
+1, ran into the same problem when trying to emulate the ActiveJob guide's example of using something like `deliver_later(wait: 5.minutes)`

**Comment by kevinjalbert** [comment]
:+1: running into this problem as well.

**Comment by brandonhilkert** [comment]
Closing in favor of #97.
