### ISSUE TITLE
passing thread-locales

### ISSUE THREAD

**Issue by phoet** [brandonhilkert/sucker_punch#96]
i'm playing around with ActiveJob and sucker_punch and i'm running into some issues with thread-locales that my app use for configuration.

there are two different aspects here:

* multitenancy via [Whitelabel](https://travis-ci.org/phoet/whitelabel)
* locale via [I18n](https://github.com/svenfuchs/i18n)

both libraries have their state in a thread-locale that i would like to pass along with an active-record object to be worked on in a job. unfortunately i did not find a good point to hook into sucker-punch/active-job to do this. do you have some recommendations?

here is what happens:

```
before_enqueue #<GeoJob:0x007fb38bfe8328> label: hamburg
around_enqueue-1 #<GeoJob:0x007fb38bfe8328> label: hamburg
block.call -->
     ActiveJob::DeserializationError:
       Error while trying to deserialize arguments: set a label before calling 'label_id'
     # ./app/models/location.rb:18:in `block in <class:Location>'
     # (celluloid):0:in `remote procedure call'
     # (celluloid):0:in `remote procedure call'
     # ./app/jobs/geo_job.rb:9:in `call'
     # ./app/jobs/geo_job.rb:9:in `block in <class:GeoJob>'
     # ./app/models/location.rb:35:in `perform_geocoding'
     # ./spec/models/location_spec.rb:6:in `block (2 levels) in <top (required)>'
```

the error is thrown from a `default_scope` that has access to a thread-locale that would need to be properly initialized before getting called.

**Comment by brandonhilkert** [comment]
Can you not pass the values in to the job?

**Comment by phoet** [comment]
@brandonhilkert i can pass the values into the job, but i'd have to pass the entity per id + class instead of passing serializing the active-record model directly.

**Comment by brandonhilkert** [comment]
Passing through IDs is a safer approach https://github.com/mperham/sidekiq/wiki/Best-Practices

I don't know why thread locals wouldn't work, but it's also hard to say without seeing the application.

**Comment by phoet** [comment]
thread locales aren't transferred to a different thread, so one would need
to pass the data and initialize it at some point before they can be
accessed. I'll try to build a minimal example to make it clear.
Am 29.01.2015 20:25 schrieb "Brandon Hilkert" <notifications@github.com>:

**Comment by phoet** [comment]
it looks like this is properly [addressed in rails-master](https://github.com/rails/rails/commit/65542e27979fce1f6b0893a00e4d51849616de34#diff-827b1c027620b4b4e8c02fa729ef9d88) with `serialize` and `deserialize` hooks for ActiveJob.
